name: Build and Push Webapp

on:
  push:
    branches: [ main, cicd-to-acr ]
    paths:
      - 'apps/webapp/**'
      - '.github/workflows/webapp-docker-build-push.yaml'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and deploy Frontend Container App
      uses: azure/container-apps-deploy-action@v2
      with:
        appSourcePath: ${{ github.workspace }}
        dockerfilePath: ./apps/webapp/Dockerfile
        imageToBuild: ${{ secrets.ACR_NAME }}.azurecr.io/webapp:latest
        acrName: ${{ secrets.ACR_NAME }}
        # containerAppName: webapp2025hack
        resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
